export type WorkforceFixture = readonly [
  employeeId: string,
  fullName: string,
  workEmail: string,
  department: string,
  location: string,
  supportTier: string,
  employmentStatus: string,
  salary: number,
  bonus: number,
  tenantId: string,
];

// Synthetic group sizes: A/Support 6, A/Finance 3, A/People 1,
// B/Finance 5, B/Support 2, and B/People 1.
export const workforceFixtures: readonly WorkforceFixture[] = [
  [
    "A-001",
    "Nia Cole",
    "nia@tenant-a.test",
    "Support",
    "Cotonou",
    "L1",
    "active",
    4200000,
    210000,
    "tenant-a",
  ],
  [
    "A-002",
    "Kojo Mills",
    "kojo@tenant-a.test",
    "Support",
    "Accra",
    "L2",
    "active",
    4700000,
    235000,
    "tenant-a",
  ],
  [
    "A-003",
    "Aya Diallo",
    "aya@tenant-a.test",
    "Support",
    "Dakar",
    "L1",
    "active",
    4300000,
    215000,
    "tenant-a",
  ],
  [
    "A-004",
    "Tobi Reed",
    "tobi@tenant-a.test",
    "Support",
    "Lagos",
    "L3",
    "active",
    5400000,
    324000,
    "tenant-a",
  ],
  [
    "A-005",
    "Lina Moyo",
    "lina@tenant-a.test",
    "Support",
    "Nairobi",
    "L2",
    "leave",
    4800000,
    240000,
    "tenant-a",
  ],
  [
    "A-006",
    "Sena Kone",
    "sena@tenant-a.test",
    "Support",
    "Abidjan",
    "L1",
    "active",
    4250000,
    212500,
    "tenant-a",
  ],
  [
    "A-007",
    "Eli Mensah",
    "eli@tenant-a.test",
    "Finance",
    "Accra",
    "L2",
    "active",
    6100000,
    488000,
    "tenant-a",
  ],
  [
    "A-008",
    "Zuri Okafor",
    "zuri@tenant-a.test",
    "Finance",
    "Lagos",
    "L3",
    "active",
    6900000,
    552000,
    "tenant-a",
  ],
  [
    "A-009",
    "Malo Dossou",
    "malo@tenant-a.test",
    "Finance",
    "Cotonou",
    "L2",
    "active",
    6250000,
    500000,
    "tenant-a",
  ],
  [
    "A-010",
    "Imani Ba",
    "imani@tenant-a.test",
    "People",
    "Dakar",
    "L2",
    "active",
    5800000,
    406000,
    "tenant-a",
  ],
  [
    "B-001",
    "Ayo Grant",
    "ayo@tenant-b.test",
    "Finance",
    "Lagos",
    "L1",
    "active",
    4500000,
    270000,
    "tenant-b",
  ],
  [
    "B-002",
    "Mira Stone",
    "mira@tenant-b.test",
    "Finance",
    "Kigali",
    "L2",
    "active",
    5100000,
    357000,
    "tenant-b",
  ],
  [
    "B-003",
    "Kofi Lane",
    "kofi@tenant-b.test",
    "Finance",
    "Accra",
    "L2",
    "active",
    5200000,
    364000,
    "tenant-b",
  ],
  [
    "B-004",
    "Amara Bell",
    "amara@tenant-b.test",
    "Finance",
    "Nairobi",
    "L3",
    "active",
    5900000,
    472000,
    "tenant-b",
  ],
  [
    "B-005",
    "Noah Etim",
    "noah@tenant-b.test",
    "Finance",
    "Abuja",
    "L1",
    "leave",
    4600000,
    276000,
    "tenant-b",
  ],
  [
    "B-006",
    "Fari Ncube",
    "fari@tenant-b.test",
    "Support",
    "Harare",
    "L1",
    "active",
    3900000,
    156000,
    "tenant-b",
  ],
  [
    "B-007",
    "Beni Lawal",
    "beni@tenant-b.test",
    "Support",
    "Abuja",
    "L2",
    "active",
    4400000,
    176000,
    "tenant-b",
  ],
  [
    "B-008",
    "Tala Nuru",
    "tala@tenant-b.test",
    "People",
    "Kigali",
    "L2",
    "active",
    5300000,
    318000,
    "tenant-b",
  ],
] as const;
